{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "995b53a1_440947e8",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 100531
      },
      "writtenOn": "2020-11-25T21:34:30Z",
      "side": 1,
      "message": "The failure is due to there being no BUG: in the commit message, I have added one now.\n ",
      "revId": "eb14064f52e03de86be42f0cfb032188f5f50317",
      "serverId": "aea13c4a-0b89-3eca-aee9-e193b1b77aa4"
    }
  ]
}